# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "my-node-app"
client_id = "3307b03ef529b67d4f045dc1b2490cf7"
application_url = "https://reserved-appear-cookie-badge.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://reserved-appear-cookie-badge.trycloudflare.com/auth/callback",
  "https://reserved-appear-cookie-badge.trycloudflare.com/auth/shopify/callback",
  "https://reserved-appear-cookie-badge.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-teton.myshopify.com"
